language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - mkdir -p dist
  - npm install

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  repo: eden-vet/eden-vet.github.io
  target_branch: master
  on:
    branch: master
